
<div class="row">
	<div class="col-md-12">
		<p class="bg-success">
			System does <?php echo $this->percolates ? '' : 'not'; ?> percolates.
		</p>
		<table class="table table-bordered percolation">
		<tbody>
		<?php $index = 0; ?>
		<?php foreach ($this->sites as $row => $rowSites) : ?>
			<tr>
				<?php foreach ($rowSites as $col => $site ): ?>
				<td class="<?php echo ( $site===0 ? 'closed' : ($site===1 ? 'open' : 'full') ) ?>"> <?php echo $index; $index++; ?></td>
				<?php endforeach ; ?>
			</tr>
		<?php endforeach ; ?>

		</tbody>
		</table>
	</div>

</div>
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Percolation Problem') ?></h3>
            </div>
            <div class="panel-body">
                <p>
					<b>Percolation.</b>
					Given a composite systems comprised of randomly distributed insulating and metallic materials: what fraction of the materials need to be metallic so that the composite system is an electrical conductor? Given a porous landscape with water on the surface (or oil below), under what conditions will the water be able to drain through to the bottom (or the oil to gush through to the surface)? Scientists have defined an abstract process known as
					<em>percolation</em>
					to model such situations.
				</p>
                <p>
					<a class="btn btn-success pull-right"
					   href="https://class.coursera.org/algs4partI-004"
					   target="_blank"><?php echo $this->translate('Algorithms, Part I') ?> &raquo;</a>
				</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
